CREATE TABLE monetary_operations
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    account_number  BIGINT,
    operation_date  DATETIME,
    beneficiary     VARCHAR(255),
    comment         VARCHAR(255),
    amount          DOUBLE,
    currency        VARCHAR(255),
);